### ISSUE TITLE
Please create conda package

### ISSUE THREAD

**Issue by pvanheus** [xavierdidelot/TransPhylo#13] opened 2019-11-01 04:38 UTC
Hi there! I could not find TransPhylo in bioconda. Please create a conda package for this software.

**Comment by dfornika** [comment] 2020-02-08 22:23
Are there any plans to submit this package to CRAN or Bioconductor?

There are some guidelines for contributing to bioconda or conda-forge, depending on which other repositories the package is made available in:

https://bioconda.github.io/contributor/guidelines.html#r-cran
https://bioconda.github.io/contributor/guidelines.html#r-bioconductor
https://bioconda.github.io/contributor/guidelines.html#r-other-sources

**Comment by xavierdidelot** [comment] 2020-02-10 13:34
Hi Dan, thanks for your message. I'm just not sure what would be gained by having this package on CRAN. Installation from github is already done with a single line, and this way I can directly control the package versions.

**Comment by dfornika** [comment] 2020-02-10 16:53
@xavierdidelot Ok, for the bioconda project it is preferable to pull from CRAN for the reasons described on their contributor guidelines linked above:

>If a package is only provided in a public repository (e.g. at github or bitbucket) or via some other website, first check with the authors of the package, if they are planning to publish it on CRAN or Bioconductor. This is always preferable, as it will ensure quality control and permanent availability at a stable URL, and can warrant waiting for such a publication. If this is not planned, you should check if a tagged version is available in a public repo...

(to be honest I'm not sure I understand what additional 'quality control' CRAN provides).

...but if there are no plans to push to CRAN or Bioconductor then we can pull directly from github since there are stable tagged versions here to pull from.

**Comment by xavierdidelot** [comment] 2020-02-10 16:57
Thanks, I can confirm there is no plan to submit to cran or bioconductor, although it could be done of course if there was enough call for it. In the meantime, pulling directly from github is the recommended method to install TransPhylo.

**Comment by dfornika** [comment] 2020-02-10 17:23
@xavierdidelot Would you be willing to add a LICENSE file to the repo and tag a release that includes that file? It's unclear which license this software is being distributed under.

**Comment by xavierdidelot** [comment] 2020-02-11 10:25
Thanks Dan, I've added the LICENSE file and tagged the current version 1.3.2. Can TransPhylo now be included in conda?

**Comment by dfornika** [comment] 2020-02-11 17:09
It looks like it already has been! Another bioconda maintainer polished up my pull-request and merged it.

It's published here:

https://anaconda.org/bioconda/r-transphylo

**Comment by xavierdidelot** [comment] 2020-02-12 08:57
That's brilliant, thanks Dan!

**Closed by xavierdidelot** 2020-02-12 08:57 UTC
